micronaut:
  application:
    name: inventoryService
  server:
    port: 32580
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
#  metrics:
#    enabled: true
#    export:
#      prometheus:
#        enabled: true
#        descriptions: true
#        step: PT1M
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/poster_db
    driverClassName: org.postgresql.Driver
    username: root
    password: root
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
    entity-scan:
      packages:
        - de.htwsaar.pimsar.grp10.domain
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        enable_lazy_load_no_trans: true
kafka:
  bootstrap:
    servers: localhost:9094
consul:
  client:
    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
    registration:
      enabled: true
