micronaut:
  application:
    name: reviewService
  server:
    port: 32581
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
#  metrics:
#    enabled: true
#    export:
#      prometheus:
#        enabled: true
#        descriptions: true
#        step: PT1M
kafka:
  bootstrap:
    servers: localhost:9094
consul:
  client:
    registration:
      enabled: true
    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
mongodb:
  uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/article-poster-reviews
  databaseName: object-review
  collectionName: reviews
